#!/usr/bin/env bash

echo  "Setting up dot files..."
BASEDIR=$(dirname $0)

# ****************************************************************
# Setup hammerspoon
ln -fvs $PWD/$BASEDIR/hammerspoon ~/.hammerspoon

# ****************************************************************
# Setup tmux
ln -fvs $PWD/$BASEDIR/tmux/tmux.conf ~/.tmux.conf

# ****************************************************************
# 替换brew.git:
cd "$(brew --repo)"
git remote set-url origin https://mirrors.ustc.edu.cn/brew.git

# 替换homebrew-core.git:
cd "$(brew --repo)/Library/Taps/homebrew/homebrew-core"
git remote set-url origin https://mirrors.ustc.edu.cn/homebrew-core.git

brew update